name: Testing Build Chrome
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Testing
        run: |
          sudo systemctl stop docker.service
          sudo systemctl stop docker.socket
          sudo rm -rf /var/lib/docker
          sudo mkdir -p /var/lib/docker

      - name: Maximize runner disk
        uses: justinthelaw/maximize-github-runner-space@master
        with:
          cleanup-profile: max

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
