name: Testing Build Chrome
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Clean Docker
        run: |
          sudo systemctl stop docker.service
          sudo systemctl stop docker.socket
          sudo rm -rf /var/lib/docker
          sudo mkdir -p /var/lib/docker

      - name: Maximize runner disk
        uses: justinthelaw/maximize-github-runner-space@master
        with:
          cleanup-profile: max

      - name: Build Chrome
        run: |
          export HOME="$GITHUB_WORKSPACE"
          export PATH="$HOME/depot_tools:$PATH"
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git "$HOME/depot_tools"
          mkdir "$HOME/chrome" && cd "$HOME/chrome"
          fetch --no-history --nohooks chromium
          cd src
          gclient runhooks
          ./build/install-build-deps.sh --arm
          mkdir out/Default
          echo "
          is_debug = false
          is_official_build = true
          v8_symbol_level=0
          blink_symbol_level=0
          dcheck_always_on = false
          chrome_pgo_phase = 0
          symbol_level = 0
          target_cpu = \"arm64\"
          " > out/Default/args.gn
          ./build/linux/sysroot_scripts/install-sysroot.py --arch=arm64
          gn gen out/Default
          autoninja -C out/Default chrome

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
