name: Test LXC
on:
  workflow_dispatch:

jobs:
  build_lxc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        platform: [x86_64]
        LXC_VERSION: ["5.0.3"]

    steps:
      - name: Set Build Architecture
        run: |
          if [ "${{ matrix.platform }}" = "aarch64" ]; then
            echo "arch_name=arm64/v8" >> $GITHUB_ENV
          elif [ "${{ matrix.platform }}" = "arm" ]; then
            echo "arch_name=arm/v7" >> $GITHUB_ENV
          elif [ "${{ matrix.platform }}" = "x86_64" ]; then
            echo "arch_name=amd64" >> $GITHUB_ENV
          fi
          
      - name: Build LXC
        run: |
          # Support for ARM and ARM64
          if [[ "${{ matrix.platform }}" == "arm" || "${{ matrix.platform }}" == "aarch64" ]]; then
              docker run --rm --privileged aptman/qus -s -- -p arm aarch64
          fi

          export LXC_VERSION="${{ matrix.LXC_VERSION }}"
          
          docker run --name lxc-builder-${{ matrix.platform }} --platform linux/${{ env.arch_name }} ubuntu:jammy bash -c ' \
              DEBIAN_FRONTEND=noninteractive apt update; \
              DEBIAN_FRONTEND=noninteractive apt install -y wget libapparmor-dev libselinux-dev libseccomp-dev libcap-dev libsystemd-dev systemd wget docbook2x meson pkg-config docbook2x cmake git libssl-dev libpam0g-dev liburing-dev; \
              mkdir -p project/build/lxc; \
              cd project/build; \
              wget "https://github.com/lxc/lxc/archive/refs/tags/lxc-'${LXC_VERSION}'.tar.gz" -O lxc.tar.gz; \
              tar xf lxc.tar.gz --strip-components=1 -C lxc; \
              cd lxc; \
              sed -i "s/cpuset\.cpus/cpus/g" src/lxc/cgroups/cgfsng.c; \
              sed -i "s/cpuset\.mems/mems/g" src/lxc/cgroups/cgfsng.c; \
              sed -i "s/cpuset\.cpus/cpus/g" src/lxc/pam/pam_cgfs.c; \
              sed -i "s/cpuset\.mems/mems/g" src/lxc/pam/pam_cgfs.c; \
              meson setup -Dprefix=/usr build || exit 1; \
              meson compile -C build || exit 1; \
              DESTDIR=dist meson install -C build; \
              cd build; \
              DIST_DIRS="$(cd dist; find . -maxdepth 1 -type d ! -name "\.")"; \
              tar -I "gzip --best" -cf "lxc-'${LXC_VERSION}'.tar.gz" -C dist ${DIST_DIRS}; \
              mv "lxc-'${LXC_VERSION}'.tar.gz" /tmp; \
          '

          docker cp lxc-builder-${{ matrix.platform }}:/tmp/lxc-${LXC_VERSION}.tar.gz .

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
